# Generated by Django 5.2.3 on 2025-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(choices=[('main_menu', 'main_menu')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
