# Generated by Django 5.2.3 on 2025-06-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_named_url_alter_menuitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
    ]
